version: '3'
services:
  subject:
    image: vaibhavrajput/compose-demo-subject
    volumes:
      - './static:/app/static'
  
  flask:
    image: vaibhavrajput/compose-demo-api
    ports:
      - "5050:5050"
    volumes:
      - './static:/app/static'
    networks:
      - front_tier

  frontend:
    image: vaibhavrajput/compose-demo-frontend
    ports:
      - "8080:8080"
    networks:
      - front_tier

networks:
  front_tier:
    external:
      name: front_tier
